PREFIX my: <http://my.org#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX vivo: <http://vivoweb.org/ontology/core#>


CONSTRUCT {
    ?org_uri a foaf:Organization .           # create an org       
    ?org_uri rdfs:label ?name .              # name the org
    
    ?org_uri vivo:abbreviation ?acronym .    # has abbreviation

    ?org_uri a ?type_uri .                   # org has type
    
    ?org_uri vivo:0002000 ?country_uri .     # org has location in country
    
    ?org_uri obo:ARG_2000028 ?vcard_uri .    # org has a vcard
    ?vcard_uri a vcard:Kind .                # vcard_uri is a vcard Kind
    ?vcard_uri vcard:hasURL ?link_uri .      # vcard has a url
    ?link_uri a vcard:URL .                  # link_uri is a vcard URL
    ?link_uri vcard:url ?link .              # url has a link value
    ?link_uri rdfs:label "Homepage"@en .     # the url is a homepage

    }

WHERE {	
    
    # org_uri and ROR id
    
    ?s my:id ?ror .
    BIND(IRI(CONCAT("http://vivoweb.org/org/ror",strafter(str(?ror), "https://ror.org/"))) AS ?org_uri)
    BIND(IRI(CONCAT(str(?org_uri),"rorid")) AS ?ror_uri)

    ?s my:name ?name .
           
    # Acronyms (abbreviation)
    
    ?s my:acronyms ?acronym .
    
    # Type (disposition)
    
    ?s my:types ?type .
    BIND( IF(?type = "Healthcare", 	vivo:Hospital, 
          IF(?type = "Education", 	vivo:University,
          IF(?type = "Company", 	vivo:Company,
          IF(?type = "Archive", 	vivo:Library,
          IF(?type = "Nonprofit", 	vivo:Company,
          IF(?type = "Government", 	vivo:GovernmentAgency, ""
    )))))) AS ?type_uri)
          
    # Country
    
    ?s my:country ?c .
    ?c my:country_code ?c_code .
    BIND(IRI(CONCAT("http://vivoweb.org/org/country",?c_code)) AS ?country_uri)
    
    # Links (home page)
    
    ?s my:links ?link .
    BIND(IRI(CONCAT(str(?org_uri),"vcard")) AS ?vcard_uri) 
    BIND(IRI(CONCAT(str(?org_uri),"homepage")) AS ?link_uri)

}
